---
configs:
  env: 'dev'
  dev:
    dockerhost:
      box: 'geerlingguy/ubuntu1604'
      name: 'dockerhost'
      forward_ports:
        - { host: 8000, guest: 8000 }
      scripts:
        - provision/setup.sh
        # Tried when I was having issues w/ shared folders but
        # it didn't help, so I'm just leaving it here, commented
        # - provision/vbox.sh
      shared_folders:
        - { host: 'apps/', guest: '/usr/local/src' }
