---
configs:
  env: 'dev'
  dev:
    dockerhost:
      box: 'geerlingguy/ubuntu1604'
      name: 'dockerhost'
      forward_ports:
        - { host: 8000, guest: 8000 }
      shared_folders:
        - { host: 'apps/', guest: '/usr/local/src', follow_symlinks: true }
      scripts:
        - { path: provision/setup.sh, args: [] }
        # Tried when I was having issues w/ shared folders but
        # it didn't help, so I'm just leaving it here, commented
        # - provision/vbox.sh
        - { path: provision/start.sh, args: ["--apps-folder=/usr/local/src"] }
