---
configs:
  env: 'dev'
  dev:
    dockerhost:
      box: 'geerlingguy/ubuntu1604'
      name: 'dockerhost'
      forward_ports:
        - { host: 5555, guest: 5555 }
      apps_folder:
        host: 'apps/'
        guest: '/usr/local/src'
#      shared_folders:
#        - { host: 'apps/', guest: '/usr/local/src', share_self: false, follow_symlinks: true }
      scripts:
        - { path: provision/setup.sh, args: [] }
        # Tried when I was having issues w/ shared folders, didn't help
        # - provision/vbox.sh
        # Not used since using docker-compose
        # - { path: provision/start.sh, args: ["--apps-folder=/usr/local/src"] }
