puzzley:
  build: ./puzzley
  ports:
    - "5555:5555"
  volumes:
    - ./puzzley:/usr/src/app
#  links:
#    - dummy
docteur-souris:
  build: ./docteur-souris
  ports:
   - "80:80"
  volumes:
    - ./docteur-souris:/usr/src/app
